<?php

namespace App;

use App\Traits\Translatable;
use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
    use Translatable;

    protected $fillable = [
        'name',
        'title',
        'description',
        'image',
        'slogan',
        'company_name',
        'location_text',
        'location_link',
        'establishment',
        'employee',
        'ceo',
        'director',
        'email',
        'social_1',
        'social_2',
        'social_3',
        'social_4',
        'social_5',
        'video_mp4',
        'video_webm',
        'bg_image_jpg',
        'map_src',
        'field_company_profile_en',
        'field_company_profile_ua',
        'field_company_profile_ru',
        'field_company_profile_de',
        'field_company_name_en',
        'field_company_name_ua',
        'field_company_name_ru',
        'field_company_name_de',
        'field_location_en',
        'field_location_ua',
        'field_location_ru',
        'field_location_de',
        'field_establishment_en',
        'field_establishment_ua',
        'field_establishment_ru',
        'field_establishment_de',
        'field_employee_en',
        'field_employee_ua',
        'field_employee_ru',
        'field_employee_de',
        'field_ceo_en',
        'field_ceo_ua',
        'field_ceo_ru',
        'field_ceo_de',
        'field_director_en',
        'field_director_ua',
        'field_director_ru',
        'field_director_de',
        'description_en',
        'description_ua',
        'description_ru',
        'description_de',
        'company_name_en',
        'company_name_ua',
        'company_name_ru',
        'company_name_de',
        'location_text_en',
        'location_text_ua',
        'location_text_ru',
        'location_text_de',
        'establishment_en',
        'establishment_ua',
        'establishment_ru',
        'establishment_de',
        'employee_en',
        'employee_ua',
        'employee_ru',
        'employee_de',
        'ceo_en',
        'ceo_ua',
        'ceo_ru',
        'ceo_de',
        'director_en',
        'director_ua',
        'director_ru',
        'director_de',
        'field_contact_us_en',
        'field_contact_us_ua',
        'field_contact_us_ru',
        'field_contact_us_de',
    ];
}
